메인페이지 api 연결
Step3-kakao-tech-campus/Team8_FE pull request #116
Opened 2023-10-31 16:30 UTC by qwer15948

## ⭐Key Changes
> 핵심 변경 사항에 대해서 적어주세요.

![image](https://github.com/Step3-kakao-tech-campus/Team8_FE/assets/48706964/794aca92-db42-4a9d-993c-e497c505fae7)

글쓰기를 제외하고, 위 화면에 보이는 모든 기능을 제작하였습니다.

1. 그룹 내 페이지 조회
- /groupId/page(name)으로 이동했을 때, 페이지 이름으로 해당 페이지를 조회합니다.
- 없는 페이지를 호출하면 404 페이지로 이동합니다.
- 메인 페이지에서 에러가 나지 않으려면 그룹 생성 완료 시 메인 페이지를 자동으로 만들어줘야 합니다.
2. 최근 변경된 페이지
- 마구마구 페이지 생성을 해서 확인한 결과 제대로 동작합니다.
- 페이지 이름 위에 커서를 올리면 밑줄이 생깁니다.
3. 좋아요 싫어요 버튼
- 초기 카운트는 페이지 조회 API에서 같이 받아옵니다.
- 버튼을 누르면 버튼 컴포넌트 내의 mutate 함수가 실행되어 갱신된 카운트를 표시합니다.
- 초기 렌더링 시 카운트값이 props로 넘어오면 바로 보여줄 수 있도록 useEffect를 사용하였습니다.

<br>

## 📌Issue
- Close #114 

<br>

## 👪To Reviewers

모든 페이지에 로그인이 필요합니다!! 기능을 확인하려면 아래의 테스트 아이디로 로그인 한 후 토큰을 받아와 instance에 추가하는 작업이 필요합니다.

```
{
    "email": "test1@test.com",
    "password": "aaaassss1"
}
```

```
// 토큰 추가
const token ='[받아온 토큰 값]';
instance.defaults.headers.common.Authorization = `Bearer ${token}`;
```

위 작업 후 메인 페이지에서 group3을 선택해 확인해보세요. group3만 그룹 생성 및 메인 페이지 생성 해두었습니다. 나머진 직접 생성하셔야 해요.

로그인 후 토큰을 저장하고 불러와 미리 붙여놓는 작업이 끝나기 전까지는 위와 같은 방법으로 확인하셔야 될 것 같습니다. ㅠㅠ
postman을 이용하면 토큰을 편하게 받아오실 수 있습니다.

+ 에러 처리를 추후에 하기로 해서 메인 페이지 컴포넌트의 에러 처리가 요상할 수 있습니다! 양해바랍니다!
+ 이제 메인 페이지와 나머지 일반 페이지들을 구분할 필요가 없어져서 나중에 컴포넌트 이름 바꾸는게 나을 수도?!

<br>

## 🐾Next Move
> 다음 개발 목표를 적어주세요

포스트 생성을 한번 해보려고 합니다.. ㅎㅎ...

2023-10-31 17:15 UTC, GangHub1970 requested changes
query key는 queryKey.ts 파일에 분리해야할것같아요.
추가적으로 그룹 선택하면 헤더에 있는 그룹 선택란도 변경되어야 할것같네요!

2023-10-31 17:29 UTC, qwer15948 commented on src/components/Page/Common/LikeDislikeButton.tsx
> +  });
querykey는 깜빡했네요! 근데 header도 제가 하나요? groupName -> groupId로 바꾸면서 바뀌어야 할 부분들이 너무 많아서 그거 하나하나 확인하면 나머지 게시글 못 건들 것 같습니다...ㅎㅎ... 이건 메인 페이지를 바꿔서 생긴 이슈가 아니라 라우터 관련 문제라서 홈페이지에서 그룹 눌러서 그룹으로 이동하게 하는 사람이 바꿔야 할 것 같은데요

2023-10-31 17:56 UTC, qwer15948 commented on src/components/Page/Common/LikeDislikeButton.tsx
> +  });
selector가 동작하는 방식이 option마다 value(현재 groupName)를 주고 해당 옵션과 동일하면 선택된걸로 나오는건데, 단순히 바꾸려면 이때 param으로 가져온 groupId로 groupName을 조회하여 Select의 value에 넣어줘야 하잖아요? 근데 Id로 name만 조회하는 API가 없어 현재 구현이 불가능합니다 😢 
비슷한 걸로 특정 그룹 조회 API가 존재하는데, 이건 비공식 검색 허용 그룹에만 적용되는 API 같습니다. 비공식 공개 그룹의 정보 조회용 API라고 소개되어 있어서요.

그리고 결국엔 저 목록도 본인이 소유한 그룹들의 리스트를 출력해줘야 해서 이건 나중에 user 부분 처리하면서 같이 하는게 맞다고 봅니다. 아니면 구조를 다 바꿔도 결국 user - 메인페이지 api 이용하는 사람이 변경해야 될 테니까요.

추후 다른 구현에도 페이지와 관련된 컴포넌트가 아니라면 최대한 건드리지 않겠습니다 😰

2023-10-31 18:03 UTC, qwer15948 commented on src/components/Page/Common/LikeDislikeButton.tsx
> +  });
앗 그리고 invalidateQueries는 리패칭 관련하여 누르고 나서 데이터가 안 바뀌는 상황에 사용하는 것으로 알고 있는데... 첫 번째 렌더링 시에도 사용을 하나요? 캐싱된 쿼리 무효화로 알고 있는데 첫 렌더링 시에는 캐싱된 값이 없지 않나요? 잘 몰라서 질문드립니다.

2023-10-31 18:09 UTC, qwer15948 commented on src/components/Page/Common/LikeDislikeButton.tsx
> +  });
그리고 invalidateQueries는 제가 안 써봐서 무슨 말인지 잘 모르겠는데 어떻게 바꿔야할지 알려주실 수 있나요? 어떻게 적용해야할지 모르겠네요. 저게 더 간단한가요

2023-10-31 23:12 UTC, GangHub1970 commented on src/components/Page/Common/LikeDislikeButton.tsx
> +  });
잘 적용하신거 같아요!

2023-11-01 08:16 UTC, GangHub1970 approved these changes
👍

2023-11-01 08:18 UTC, merged