그룹원조회 api연결
Step3-kakao-tech-campus/Team8_FE pull request #144
Opened 2023-11-03 05:45 UTC by GangHub1970

## ⭐Key Changes

1. 그룹원조회 api연결
2. groupName에서 groupId로 변경되면서 그룹 마이페이지에서 헤더가 그룹선택전과 같이 나타나는 오류 해결

<br>

## 📌Issue

- close #143 

<br>

## 👪To Reviewers

api를 토요일에 배포해준다해서 마냥 기다릴순없어서 안되는건 계속 json파일로 대체하겠습니다..!
해놓고 실제로 변경했을때 안되는거 살짝 수정하는게 더 괜찮다고 생각해서..😅

2023-11-04 16:30 UTC, publdaze approved these changes
먼저 approve 해둘게요~~!

2023-11-04 16:30 UTC, publdaze commented on src/apis/groupApi.ts
> +export const getGroupMemberFn = (groupId?: string) =>
여기도 `number`로 처리해주는 걸로?

2023-11-04 16:34 UTC, publdaze requested changes

2023-11-04 16:34 UTC, publdaze commented on src/apis/groupApi.ts
> +
<img width="503" alt="image" src="https://github.com/Step3-kakao-tech-campus/Team8_FE/assets/78250089/30d17e97-82a3-40af-a945-68905e806b49">

엇 여기 eslint 때문에 에러 뜨는 듯 하네요! 개행 없애줘야 하나봐요!

2023-11-05 05:16 UTC, publdaze requested changes

2023-11-05 05:16 UTC, publdaze commented on src/components/Modal/GroupMemberListModal.tsx
> +            <ListItem key={uuidv4()}>{nickName}</ListItem>
`data`가 아직 api 응답 받아오지 못한 경우 `undefind` 값을 가지기 때문에 아래와 같이 `nickNames`을 받아오지 못해 에러가 발생하는 경우가 있는 것 같아요!

<img width="400" alt="image" src="https://github.com/Step3-kakao-tech-campus/Team8_FE/assets/78250089/f1fbe69e-4c92-4615-b5bc-d9e1bd7ad780">

옵셔널 체이닝으로 주면 좋을 것 같습니다!

```suggestion
          {data?.nickNames.map((nickName: string) => (
            <ListItem key={uuidv4()}>{nickName}</ListItem>
```

2023-11-05 06:00 UTC, publdaze approved these changes
먼저 approve 해두겠습니다! 그룹원 목록 조회 잘 되네요! 👍

2023-11-05 06:00 UTC, publdaze commented on src/components/Modal/GroupMemberListModal.tsx
> +            <ListItem key={uuidv4()}>{nickName}</ListItem>
아 이건 위에서 `isLoading` 한번 걸러줘서 아직 api 응답 받아오지 못한 경우에 대해서는 처리가 되고 있겠군요! isError인 상황에서는 아마 이부분 걸릴 것 같은데 안전빵으로 옵셔널 처리해주는 게 어떨까해요!

2023-11-05 06:00 UTC, qwer15948 approved these changes
확인했습니다!

2023-11-05 06:00 UTC, merged