포스트수정 UI구현(textarea)
Step3-kakao-tech-campus/Team8_FE pull request #78
Opened 2023-10-12 14:51 UTC by GangHub1970

## ⭐Key Changes

1. 포스트수정 UI구현을 에디터 대신 textarea로 대체해서 구현

<br>

## 📌Issue

- #62

<br>

## 👪To Reviewers

textarea로 일단 페이지만 구성해놨습니다..!

<br>

## 🐾Next Move

이제 에디터로 바꿔볼게요. 도전~

2023-10-12 22:53 UTC, qwer15948 requested changes
버튼 로직은 에디터 바꾸면서 수정해도 괜찮을 것 같은데 프롭스 이름은 헷갈릴 수 있으니 해당 풀리퀘에 바꿔주시면 좋을 것 같습니다! 😺

2023-10-12 22:53 UTC, qwer15948 commented on src/components/PageContainer.tsx
> +const PageContainer = ({ children, pageId, recentChangeList }: PageContainerProps) => {
프롭스 boolean인데 recentChangeList는 컴포넌트를 넘겨주는 느낌이라 has를 붙이거나 차라리 variant = 'both' | 'index' 등으로 바꾸는거 어떨까요?

2023-10-12 22:53 UTC, qwer15948 commented on src/pages/PostEditPage.tsx
> +            <Button ripple={false} className='py-2 rounded-md hover:shadow-none' onClick={() => navigate(-1)}>
저장 버튼 온클릭은 핸들러로 빼고 취소 버튼에 뒤로가기를 달아두는게 추후에 편할 것 같습니다!

2023-10-13 00:47 UTC, GangHub1970 commented on src/components/PageContainer.tsx
> +const PageContainer = ({ children, pageId, recentChangeList }: PageContainerProps) => {
variant = 'both' | 'index' 이게 좋아보이는데 variant='both' 값을 줘도 pageId 유무에 따라 목차 유무가 달라져서 both를 사용할때는 pagId를 같이 써줘야하기 때문에 이름에 has를 붙였습니다!

2023-10-13 00:52 UTC, GangHub1970 commented on src/pages/PostEditPage.tsx
> +            <Button ripple={false} className='py-2 rounded-md hover:shadow-none' onClick={() => navigate(-1)}>
뒤로가기는 취소 버튼으로 옮기고, 저장버튼에는 그냥 핸들러만 등록해놨습니다 👍

2023-10-13 00:57 UTC, qwer15948 approved these changes
고생 많으셨습니다! 에디터 파이팅!!! 👍

2023-10-13 00:57 UTC, merged